---
title: "**Factor relevelling example**"
subtitle: |
  | A Practical Foray into Lengthy Subtitle Management, Iris Dataset Tampering, 
  | and the Unceasing Pursuit of Stakeholder-Friendly Data Presentation.
  | From Markdown Mastery to Factor Finagling: 
author: 
  name: "Márton Kiss MD"
committee:
  - name: Márton Kiss MD
    position: Applied Biostatistician
date: 4242.10.11
number_Sections: yes
sign_page: true
output:
  pagedown::thesis_paged: 
    # # DO NOT overwrite the default css-s! Breaks the pagination
    #  - default-fonts
    #  - default-page
    #  - styles.css
    #css:
    lof: true
    lot: true
    toc: true
    toc-title: Contents
    template:
      template_pdflike.html
  html_document:
    df_print: paged
    keep_tex: yes
    fig_caption: yes
    toc: no
    css: styles.css
bibliography: packages.bib # Causes crash??
link-citations: yes
---



# Summary {.chapter}

This is a lightweight document for me to kink out the particulars of producing serious-looking but verstile documents. Rendering for 10 minutes would be unpalatable for this document, however I wanted it to serve some useful purpose besides flaunting my template.


# Relevelling & *Forcats* {.chapter}

Factors sometimes get on my nerve. Their levels' order keep changing, you want to switch between human readable (stakeholder readable) and easy-to-type names, etc.

Take a look at the *'iris'* dataset. Species is clearly a factor.



```r
unique(iris$Species)
```

[1] setosa     versicolor virginica 
Levels: setosa versicolor virginica

Lets rename some species. The below code is a bit bloated but intuitive IMHO.


```r
library(dplyr)

iris_recode <- iris %>%
  mutate(Species_hr = 
           forcats::fct_recode( Species, 
                                 smelly = as.character(unique(iris$Species)[1]),
                                 fluffy = as.character(unique(iris$Species)[2])
                                 #Didn't recode 'virginica' as an example
                                 ))
```

And to test the results, lets see what a printout would say. Can I reference said table? Lets try (\@ref(tab:atable)):


```r
source(here::here("R","theme_marty_flextable.r"))

set.seed(12345)

iris_recode %>%
  .[sort(sample(nrow(.),10)),] %>% 
  flextable::flextable() %>%
  theme_marty() 
```

<div class="tabwid"><style>.cl-17a7b418{}.cl-179b9804{font-family:'Times New Roman';font-size:9pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-179b980e{font-family:'Times New Roman';font-size:9pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-17a01820{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-17a0182a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-17a03224{width:0.75in;background-color:rgba(204, 204, 204, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a0322e{width:0.75in;background-color:rgba(204, 204, 204, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 1.5pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a03238{width:0.75in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a03242{width:0.75in;background-color:rgba(242, 242, 242, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a0324c{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a0324d{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a03256{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-17a03260{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.tabwid {
  font-size: initial;
  padding-bottom: 1em;
}

.tabwid table{
  border-spacing:0px !important;
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  border-color: transparent;
  caption-side: top;
}
.tabwid-caption-bottom table{
  caption-side: bottom;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td, .tabwid th {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
.katex-display {
    margin: 0 0 !important;
}</style><table data-quarto-disable-processing='true' class='cl-17a7b418'><thead><tr style="overflow-wrap:break-word;"><th class="cl-17a03224"><p class="cl-17a01820"><span class="cl-179b9804">Sepal.Length</span></p></th><th class="cl-17a03224"><p class="cl-17a01820"><span class="cl-179b9804">Sepal.Width</span></p></th><th class="cl-17a03224"><p class="cl-17a01820"><span class="cl-179b9804">Petal.Length</span></p></th><th class="cl-17a03224"><p class="cl-17a01820"><span class="cl-179b9804">Petal.Width</span></p></th><th class="cl-17a0322e"><p class="cl-17a0182a"><span class="cl-179b9804">Species</span></p></th><th class="cl-17a0322e"><p class="cl-17a0182a"><span class="cl-179b9804">Species_hr</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">4.90</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">3.00</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">1.40</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">0.20</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">setosa</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">smelly</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">4.90</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">3.60</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">1.40</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">0.10</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">setosa</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">smelly</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">7.00</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">3.20</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">4.70</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">1.40</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">versicolor</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">fluffy</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">4.90</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">2.40</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">3.30</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">1.00</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">versicolor</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">fluffy</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">6.40</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">2.90</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">4.30</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">1.30</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">versicolor</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">fluffy</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">6.00</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">3.40</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">4.50</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">1.60</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">versicolor</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">fluffy</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">5.80</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">2.60</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">4.00</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">1.20</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">versicolor</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">fluffy</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">5.70</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">3.00</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">4.20</span></p></td><td class="cl-17a0324c"><p class="cl-17a01820"><span class="cl-179b980e">1.20</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">versicolor</span></p></td><td class="cl-17a0324d"><p class="cl-17a0182a"><span class="cl-179b980e">fluffy</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">6.90</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">3.10</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">5.10</span></p></td><td class="cl-17a03238"><p class="cl-17a01820"><span class="cl-179b980e">2.30</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">virginica</span></p></td><td class="cl-17a03242"><p class="cl-17a0182a"><span class="cl-179b980e">virginica</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-17a03256"><p class="cl-17a01820"><span class="cl-179b980e">6.70</span></p></td><td class="cl-17a03256"><p class="cl-17a01820"><span class="cl-179b980e">3.00</span></p></td><td class="cl-17a03256"><p class="cl-17a01820"><span class="cl-179b980e">5.20</span></p></td><td class="cl-17a03256"><p class="cl-17a01820"><span class="cl-179b980e">2.30</span></p></td><td class="cl-17a03260"><p class="cl-17a0182a"><span class="cl-179b980e">virginica</span></p></td><td class="cl-17a03260"><p class="cl-17a0182a"><span class="cl-179b980e">virginica</span></p></td></tr></tbody></table></div>

# Notes

Information regarding the compilation of this document:

<!---
Example of printing chunk stuff without the hideous '##' 
--->


```r
knitr::opts_chunk$set(comment = NA)
sessionInfo() %>% report::report() %>% cat()
```

Analyses were conducted using the R Statistical language (version 4.3.0; R Core Team, 2023) on Windows 10 x64 (build 19045), using the packages rmarkdown (version 2.23; Allaire J et al., 2023), effects (version 4.2.2; Fox J, Weisberg S, 2019), carData (version 3.0.5; Fox J et al., 2022), flextable (version 0.9.2; Gohel D, Skintzos P, 2023), lubridate (version 1.9.2; Grolemund G, Wickham H, 2011), DHARMa (version 0.4.6; Hartig F, 2022), huxtable (version 5.5.2; Hugh-Jones D, 2022), labelled (version 2.12.0; Larmarange J, 2023), emmeans (version 1.8.7; Lenth R, 2023), nlme (version 3.1.162; Pinheiro J et al., 2023), gtsummary (version 1.7.1; Sjoberg D et al., 2021), ggplot2 (version 3.4.2; Wickham H, 2016), readxl (version 1.4.2; Wickham H, Bryan J, 2023), roxygen2 (version 7.2.3; Wickham H et al., 2022), dplyr (version 1.1.2; Wickham H et al., 2023), knitr (version 1.43; Xie Y, 2023), pagedown (version 0.20; Xie Y et al., 2022) and kableExtra (version 1.3.4.9000; Zhu H, 2023).

References
----------
  - Allaire J, Xie Y, Dervieux C, McPherson J, Luraschi J, Ushey K, Atkins A, Wickham H, Cheng J, Chang W, Iannone R (2023). _rmarkdown: Dynamic Documents for R_. R package version 2.23, <https://github.com/rstudio/rmarkdown>. Xie Y, Allaire J, Grolemund G (2018). _R Markdown: The Definitive Guide_. Chapman and Hall/CRC, Boca Raton, Florida. ISBN 9781138359338, <https://bookdown.org/yihui/rmarkdown>. Xie Y, Dervieux C, Riederer E (2020). _R Markdown Cookbook_. Chapman and Hall/CRC, Boca Raton, Florida. ISBN 9780367563837, <https://bookdown.org/yihui/rmarkdown-cookbook>.
  - Fox J, Weisberg S (2019). _An R Companion to Applied Regression_, 3rd edition. Sage, Thousand Oaks CA. <https://socialsciences.mcmaster.ca/jfox/Books/Companion/index.html>. Fox J, Weisberg S (2018). "Visualizing Fit and Lack of Fit in Complex Regression Models with Predictor Effect Plots and Partial Residuals." _Journal of Statistical Software_, *87*(9), 1-27. doi:10.18637/jss.v087.i09 <https://doi.org/10.18637/jss.v087.i09>. Fox J (2003). "Effect Displays in R for Generalised Linear Models." _Journal of Statistical Software_, *8*(15), 1-27. doi:10.18637/jss.v008.i15 <https://doi.org/10.18637/jss.v008.i15>. Fox J, Hong J (2009). "Effect Displays in R for Multinomial and Proportional-Odds Logit Models: Extensions to the effects Package." _Journal of Statistical Software_, *32*(1), 1-24. doi:10.18637/jss.v032.i01 <https://doi.org/10.18637/jss.v032.i01>.
  - Fox J, Weisberg S, Price B (2022). _carData: Companion to Applied Regression Data Sets_. R package version 3.0-5, <https://CRAN.R-project.org/package=carData>.
  - Gohel D, Skintzos P (2023). _flextable: Functions for Tabular Reporting_. R package version 0.9.2, <https://CRAN.R-project.org/package=flextable>.
  - Grolemund G, Wickham H (2011). "Dates and Times Made Easy with lubridate." _Journal of Statistical Software_, *40*(3), 1-25. <https://www.jstatsoft.org/v40/i03/>.
  - Hartig F (2022). _DHARMa: Residual Diagnostics for Hierarchical (Multi-Level / Mixed) Regression Models_. R package version 0.4.6, <https://CRAN.R-project.org/package=DHARMa>.
  - Hugh-Jones D (2022). _huxtable: Easily Create and Style Tables for LaTeX, HTML and Other Formats_. R package version 5.5.2, <https://CRAN.R-project.org/package=huxtable>.
  - Larmarange J (2023). _labelled: Manipulating Labelled Data_. R package version 2.12.0, <https://CRAN.R-project.org/package=labelled>.
  - Lenth R (2023). _emmeans: Estimated Marginal Means, aka Least-Squares Means_. R package version 1.8.7, <https://CRAN.R-project.org/package=emmeans>.
  - Pinheiro J, Bates D, R Core Team (2023). _nlme: Linear and Nonlinear Mixed Effects Models_. R package version 3.1-162, <https://CRAN.R-project.org/package=nlme>. Pinheiro JC, Bates DM (2000). _Mixed-Effects Models in S and S-PLUS_. Springer, New York. doi:10.1007/b98882 <https://doi.org/10.1007/b98882>.
  - R Core Team (2023). _R: A Language and Environment for Statistical Computing_. R Foundation for Statistical Computing, Vienna, Austria. <https://www.R-project.org/>.
  - Sjoberg D, Whiting K, Curry M, Lavery J, Larmarange J (2021). "Reproducible Summary Tables with the gtsummary Package." _The R Journal_, *13*, 570-580. doi:10.32614/RJ-2021-053 <https://doi.org/10.32614/RJ-2021-053>, <https://doi.org/10.32614/RJ-2021-053>.
  - Wickham H (2016). _ggplot2: Elegant Graphics for Data Analysis_. Springer-Verlag New York. ISBN 978-3-319-24277-4, <https://ggplot2.tidyverse.org>.
  - Wickham H, Bryan J (2023). _readxl: Read Excel Files_. R package version 1.4.2, <https://CRAN.R-project.org/package=readxl>.
  - Wickham H, Danenberg P, Csárdi G, Eugster M (2022). _roxygen2: In-Line Documentation for R_. R package version 7.2.3, <https://CRAN.R-project.org/package=roxygen2>.
  - Wickham H, François R, Henry L, Müller K, Vaughan D (2023). _dplyr: A Grammar of Data Manipulation_. R package version 1.1.2, <https://CRAN.R-project.org/package=dplyr>.
  - Xie Y (2023). _knitr: A General-Purpose Package for Dynamic Report Generation in R_. R package version 1.43, <https://yihui.org/knitr/>. Xie Y (2015). _Dynamic Documents with R and knitr_, 2nd edition. Chapman and Hall/CRC, Boca Raton, Florida. ISBN 978-1498716963, <https://yihui.org/knitr/>. Xie Y (2014). "knitr: A Comprehensive Tool for Reproducible Research in R." In Stodden V, Leisch F, Peng RD (eds.), _Implementing Reproducible Computational Research_. Chapman and Hall/CRC. ISBN 978-1466561595.
  - Xie Y, Lesur R, Thorne B, Tan X (2022). _pagedown: Paginate the HTML Output of R Markdown with CSS for Print_. R package version 0.20, <https://CRAN.R-project.org/package=pagedown>.
  - Zhu H (2023). _kableExtra: Construct Complex Table with 'kable' and Pipe Syntax_. http://haozhu233.github.io/kableExtra/, https://github.com/haozhu233/kableExtra.

This document was compiled at:


```r
Sys.time()
```

```
[1] "2023-07-06 17:38:02 CEST"
```

```r
save.image(file = here::here("inst","states","cookbook_out.Rdata"))
```


# Appendix

This is how put all your code into an appendix.


```r
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = 'center',
                      warning = FALSE,
                      message = FALSE)

unique(iris$Species)

library(dplyr)

iris_recode <- iris %>%
  mutate(Species_hr = 
           forcats::fct_recode( Species, 
                                 smelly = as.character(unique(iris$Species)[1]),
                                 fluffy = as.character(unique(iris$Species)[2])
                                 #Didn't recode 'virginica' as an example
                                 ))

source(here::here("R","theme_marty_flextable.r"))

set.seed(12345)

iris_recode %>%
  .[sort(sample(nrow(.),10)),] %>% 
  flextable::flextable() %>%
  theme_marty() 


knitr::opts_chunk$set(comment = NA)
sessionInfo() %>% report::report() %>% cat()

Sys.time()
save.image(file = here::here("inst","states","cookbook_out.Rdata"))

# This throws a warning everytime so lets forget about it
#| tidy=TRUE
```
