---
title: "Not shown"
output:
  pdf_document: 
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    keep_tex: yes
    fig_caption: yes
    toc: yes
    number_sections: yes
  word_document: 
    fig_caption: yes
    keep_tex: yes
    toc: yes
header-includes:
  \usepackage{multicol}
  \usepackage{float}
  \usepackage{afterpage}
---

<!---
Atzs munkája nyomán (copy-paste-tel)

A header-be még ezek kellettek volna, de kivettem, helyette az egész envir.-t frissítem:

params:
  x: !r c("cyl")
  top_level: 1
  figname_prefix: h0
  
Ezt ugyan használja a file, de nem tudja felülírni a load() paranccsal a régi env.-ből a beolvasandó rdata.
--->

```{r, include=F}

# Defining stuff, including the renaming scheme, and the structure of the output

if(!exists("child_counter")) {
  child_counter <- 1
} else {
  child_counter <- child_counter + 1
}

if(!exists("params")) {
    params <- list(x              = "cyl",
                   top_level      = 2,
                   figname_prefix = "cyl"
    )
}

knitr::opts_chunk$set(fig.process = function(x) {
  x2 <- knitr::opts_current$get("label") %>%
          paste0(., '-') %>%
            sub(., '', x, fixed = T) %>%
              paste0(fig_directory,"/",.)
  if (file.rename(x, x2)) x2 else x
})


```

#`r paste(rep("#", params$top_level - 1), collapse = "")` Table

```{r, results='asis'}

mtcars[[params$x]] %>%
  as.data.frame %>%
  `colnames<-`(params$x) %>%
  tbl_summary() %>%
  martys_table_style(caption. = paste0("Frequency of ",params$x," categories"))

```


#`r paste(rep("#", params$top_level - 1), collapse = "")` Figures

```{r,}
#| fig.cap=paste0('\\label{fig:param_plot1', 
#| child_counter, '}Figure 1 from the cyclic call No.',child_counter),
#| out.width='45%',
#| fig.align='center', tidy=F, results='hide', collapse=T,

# fig.path=paste0(fig_directory, params$figname_prefix, '-fig1-')

mtcars %>%
  ggplot( aes(x = mpg,
          y = .data[[params$x]])) +
  theme_default_ggplot +
  geom_point()



```

```{r,}
#| fig.cap=paste0('\\label{fig:param_plot1', 
#| child_counter, '}Figure 2 from the cyclic call No.',child_counter),
#| out.width='45%',
#| fig.align='center', tidy=F, results='hide', collapse=T,

# fig.path=paste0(fig_directory, params$figname_prefix, '-fig1-')


mtcars %>%
  ggplot( aes(x = qsec,
          y = .data[[params$x]])) +
  theme_default_ggplot +
  geom_point()

```

<!-- És még hivatkozni is tudunk a(z) \ref{fig:param_plot1`r child_counter`}. ábrára. -->

```{r}


# resetting stuff
knitr::opts_chunk$set(
  fig.process = NULL # Critical, leads to nasty complications if removed
                      # This auto-renames output figs and is called afterwards if not reset

  )

```

\newpage

